/**
 * Castle Security & Quality Gate — State Model
 * 
 * Defines the operational release gate lifecycle states.
 * Note: These are distinct from CQS normative results (PASS, FAIL, N/A, UNEXECUTED).
 */

'use strict';

const GATE_STATE_NOT_STARTED = 'NOT_STARTED';
const GATE_STATE_IN_PROGRESS = 'IN_PROGRESS';
const GATE_STATE_EVIDENCE_PENDING = 'EVIDENCE_PENDING';
const GATE_STATE_EVALUATION_PENDING = 'EVALUATION_PENDING';
const GATE_STATE_BLOCKED = 'BLOCKED';
const GATE_STATE_CONDITIONAL = 'CONDITIONAL';
const GATE_STATE_PASSED = 'PASSED';
const GATE_STATE_REQUIRES_REMEDIATION = 'REQUIRES_REMEDIATION';
const GATE_STATE_VERIFICATION_PENDING = 'VERIFICATION_PENDING';
const GATE_STATE_CLOSED = 'CLOSED';

const PROPOSED_GATE_STATES = Object.freeze([
  GATE_STATE_NOT_STARTED,
  GATE_STATE_IN_PROGRESS,
  GATE_STATE_EVIDENCE_PENDING,
  GATE_STATE_EVALUATION_PENDING,
  GATE_STATE_BLOCKED,
  GATE_STATE_CONDITIONAL,
  GATE_STATE_PASSED,
  GATE_STATE_REQUIRES_REMEDIATION,
  GATE_STATE_VERIFICATION_PENDING,
  GATE_STATE_CLOSED
]);

module.exports = {
  GATE_STATE_NOT_STARTED,
  GATE_STATE_IN_PROGRESS,
  GATE_STATE_EVIDENCE_PENDING,
  GATE_STATE_EVALUATION_PENDING,
  GATE_STATE_BLOCKED,
  GATE_STATE_CONDITIONAL,
  GATE_STATE_PASSED,
  GATE_STATE_REQUIRES_REMEDIATION,
  GATE_STATE_VERIFICATION_PENDING,
  GATE_STATE_CLOSED,
  PROPOSED_GATE_STATES
};
