/**
 * ============================================================================
 * GRUPO CASTILLO — ROLES Y CONTROL DE ACCESO (RBAC) (v1.1)
 * ============================================================================
 * Define los tres roles fundamentales y sus capacidades estrictas:
 * - CLIENTE: Consulta de su propio proyecto, pagos, aprobaciones, tickets.
 * - INGENIERO: Proyectos asignados, ejecución técnica, hitos, staging, resolución de tickets.
 * - ADMINISTRACION: Control global, finanzas, asignaciones, autorizaciones de estado, gobernanza.
 */

export const ROLES = {
  CLIENTE: 'CLIENTE',
  INGENIERO: 'INGENIERO',
  ADMINISTRACION: 'ADMINISTRACION'
};

export const CAPABILITIES = {
  // Proyectos y estados
  VIEW_OWN_PROJECT: 'VIEW_OWN_PROJECT',
  VIEW_ASSIGNED_PROJECTS: 'VIEW_ASSIGNED_PROJECTS',
  VIEW_ALL_PROJECTS: 'VIEW_ALL_PROJECTS',
  ACCEPT_QUOTATION: 'ACCEPT_QUOTATION',
  SIGN_CONTRACT: 'SIGN_CONTRACT',
  PROPOSE_STATE_TRANSITION: 'PROPOSE_STATE_TRANSITION',
  AUTHORIZE_STATE_TRANSITION: 'AUTHORIZE_STATE_TRANSITION',
  ASSIGN_ENGINEER: 'ASSIGN_ENGINEER',
  FREEZE_PROJECT: 'FREEZE_PROJECT',
  REACTIVATE_PROJECT: 'REACTIVATE_PROJECT',

  // Hitos y Entregables
  UPDATE_MILESTONE_PROGRESS: 'UPDATE_MILESTONE_PROGRESS',
  APPROVE_MILESTONE: 'APPROVE_MILESTONE',
  PREPARE_PREDELIVERY_STAGING: 'PREPARE_PREDELIVERY_STAGING',
  AUTHORIZE_PREDELIVERY: 'AUTHORIZE_PREDELIVERY',
  APPROVE_PREDELIVERY: 'APPROVE_PREDELIVERY',
  REPORT_PREDELIVERY_OBSERVATIONS: 'REPORT_PREDELIVERY_OBSERVATIONS',
  AUTHORIZE_DELIVERY: 'AUTHORIZE_DELIVERY',
  CONFIRM_DELIVERY_RECEIPT: 'CONFIRM_DELIVERY_RECEIPT',

  // Finanzas y Pagos
  SUBMIT_PAYMENT: 'SUBMIT_PAYMENT',
  VERIFY_PAYMENT_MANUAL: 'VERIFY_PAYMENT_MANUAL',
  PROCESS_REFUND: 'PROCESS_REFUND',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',

  // Tickets y Soporte
  CREATE_TICKET: 'CREATE_TICKET',
  REPLY_TICKET: 'REPLY_TICKET',
  ASSIGN_TICKET_ENGINEER: 'ASSIGN_TICKET_ENGINEER',
  CHANGE_TICKET_SEVERITY: 'CHANGE_TICKET_SEVERITY',
  RESOLVE_TICKET: 'RESOLVE_TICKET',
  CONFIRM_TICKET_RESOLVED_CLIENT: 'CONFIRM_TICKET_RESOLVED_CLIENT',

  // Documentos y Auditoría
  UPLOAD_EVIDENCE: 'UPLOAD_EVIDENCE',
  DOWNLOAD_DOCUMENT: 'DOWNLOAD_DOCUMENT',
  VIEW_AUDIT_TRAIL: 'VIEW_AUDIT_TRAIL'
};

const ROLE_PERMISSIONS = {
  [ROLES.CLIENTE]: new Set([
    CAPABILITIES.VIEW_OWN_PROJECT,
    CAPABILITIES.ACCEPT_QUOTATION,
    CAPABILITIES.SIGN_CONTRACT,
    CAPABILITIES.SUBMIT_PAYMENT,
    CAPABILITIES.APPROVE_PREDELIVERY,
    CAPABILITIES.REPORT_PREDELIVERY_OBSERVATIONS,
    CAPABILITIES.CONFIRM_DELIVERY_RECEIPT,
    CAPABILITIES.CREATE_TICKET,
    CAPABILITIES.REPLY_TICKET,
    CAPABILITIES.CONFIRM_TICKET_RESOLVED_CLIENT,
    CAPABILITIES.UPLOAD_EVIDENCE,
    CAPABILITIES.DOWNLOAD_DOCUMENT
  ]),

  [ROLES.INGENIERO]: new Set([
    CAPABILITIES.VIEW_ASSIGNED_PROJECTS,
    CAPABILITIES.PROPOSE_STATE_TRANSITION,
    CAPABILITIES.UPDATE_MILESTONE_PROGRESS,
    CAPABILITIES.PREPARE_PREDELIVERY_STAGING,
    CAPABILITIES.CREATE_TICKET,
    CAPABILITIES.REPLY_TICKET,
    CAPABILITIES.RESOLVE_TICKET,
    CAPABILITIES.UPLOAD_EVIDENCE,
    CAPABILITIES.DOWNLOAD_DOCUMENT
  ]),

  [ROLES.ADMINISTRACION]: new Set(Object.values(CAPABILITIES))
};

/**
 * Comprueba si un rol ostenta una capacidad específica.
 * @param {string} role
 * @param {string} capability
 * @returns {boolean}
 */
export function hasCapability(role, capability) {
  if (!role || !capability) return false;
  const permissions = ROLE_PERMISSIONS[role];
  return permissions ? permissions.has(capability) : false;
}
